# Default values for stockmanagerchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3


# values.yaml
apps:
  - name: productcatalogue
    image: "henriksin1/productcatalogue:latest"
    port: 8020

  - name: shopfront
    image: "henriksin1/shopfront:latest"
    port: 8030


  - name: stockmanager
    image: "henriksin1/stockmanager:latest"
    port: 8010

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
