{{- range $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
spec:
  selector:
    app: {{ $app.name }}
  ports:
    - protocol: TCP
      port: {{ $app.port }}
      targetPort: {{ $app.port }}
{{- end }}
