apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  selector:
    matchLabels:
      app: productcatalogue
  replicas: 3
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: henriksin1/productcatalogue:v1
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8020
        readinessProbe:
          httpGet:
            path: /
            port: 8025
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
spec:
  type: LoadBalancer
  selector:
    app: productcatalogue
  ports:
  - port: 8020
    name: http
    protocol: TCP
