apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
spec:
  selector:
    matchLabels:
      app: shopfront
  replicas: 5
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: henriksin1/shopfront:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - port: 8010
    name: http
    protocol: TCP
