name: productcatalogue Java CI 

on:
  push:
    branches: 
      - main

jobs:
  build-deploy:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Build with Maven
      run: |
          cd productcatalogue
          mvn -B package -DskipTests --file pom.xml
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: productcatalogue/.
        file: productcatalogue/Dockerfile
        push: true
        tags: henriksin1/productcatalogue:v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: update kube config
      run: aws eks --region us-east-1 update-kubeconfig --name cluster-test

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes-manifest/productcatalogue-deployment.yaml
